// Code generated by vipsgen. DO NOT EDIT.
#ifndef GEN_HISTOGRAM_H
#define GEN_HISTOGRAM_H

#include <stdlib.h>
#include <vips/vips.h>

int gen_vips_hist_cum(VipsImage * input, VipsImage ** out_out);

int gen_vips_hist_entropy(VipsImage * input, double * out_out);

typedef struct {
    int has_band;
    int band;
} GenHistEqualOpts;

int gen_vips_hist_equal(VipsImage * input, VipsImage ** out_out, GenHistEqualOpts *opts);

int gen_vips_hist_ismonotonic(VipsImage * input, int * out_monotonic);

typedef struct {
    int has_maxSlope;
    int maxSlope;
} GenHistLocalOpts;

int gen_vips_hist_local(VipsImage * input, int width, int height, VipsImage ** out_out, GenHistLocalOpts *opts);

int gen_vips_hist_match(VipsImage * input, VipsImage * ref, VipsImage ** out_out);

int gen_vips_hist_norm(VipsImage * input, VipsImage ** out_out);

int gen_vips_hist_plot(VipsImage * input, VipsImage ** out_out);

typedef struct {
    int has_band;
    int band;
} GenMaplutOpts;

int gen_vips_maplut(VipsImage * input, VipsImage * lut, VipsImage ** out_out, GenMaplutOpts *opts);

int gen_vips_percent(VipsImage * input, double percent, int * out_threshold);

typedef struct {
    int has_s0;
    double s0;
    int has_b;
    double b;
    int has_m0;
    double m0;
    int has_a;
    double a;
} GenStdifOpts;

int gen_vips_stdif(VipsImage * input, int width, int height, VipsImage ** out_out, GenStdifOpts *opts);

#endif
