// Code generated by vipsgen. DO NOT EDIT.
#include "gen_colour.h"

int gen_vips_CMC2LCh(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("CMC2LCh");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_CMYK2XYZ(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("CMYK2XYZ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_HSV2sRGB(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("HSV2sRGB");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LCh2CMC(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LCh2CMC");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LCh2Lab(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LCh2Lab");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Lab2LCh(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Lab2LCh");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Lab2LabQ(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Lab2LabQ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Lab2LabS(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Lab2LabS");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Lab2XYZ(VipsImage * input, VipsImage ** out_out, GenLab2XYZOpts *opts) {
    VipsOperation *op = vips_operation_new("Lab2XYZ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_temp) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->temp, opts->temp_n);
                vips_object_set(VIPS_OBJECT(op), "temp", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LabQ2Lab(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LabQ2Lab");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LabQ2LabS(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LabQ2LabS");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LabQ2sRGB(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LabQ2sRGB");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LabS2Lab(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LabS2Lab");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_LabS2LabQ(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("LabS2LabQ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Oklab2Oklch(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Oklab2Oklch");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Oklab2XYZ(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Oklab2XYZ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Oklch2Oklab(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Oklch2Oklab");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_XYZ2CMYK(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("XYZ2CMYK");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_XYZ2Lab(VipsImage * input, VipsImage ** out_out, GenXYZ2LabOpts *opts) {
    VipsOperation *op = vips_operation_new("XYZ2Lab");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_temp) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->temp, opts->temp_n);
                vips_object_set(VIPS_OBJECT(op), "temp", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_XYZ2Oklab(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("XYZ2Oklab");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_XYZ2Yxy(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("XYZ2Yxy");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_XYZ2scRGB(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("XYZ2scRGB");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_Yxy2XYZ(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("Yxy2XYZ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_dE00(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("dE00");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_dE76(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("dE76");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_dECMC(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("dECMC");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_float2rad(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("float2rad");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_icc_export(VipsImage * input, VipsImage ** out_out, GenIccExportOpts *opts) {
    VipsOperation *op = vips_operation_new("icc_export");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_pcs) {
            vips_object_set(VIPS_OBJECT(op), "pcs", (int)opts->pcs, NULL);
        }
        if (opts->has_intent) {
            vips_object_set(VIPS_OBJECT(op), "intent", (int)opts->intent, NULL);
        }
        if (opts->has_blackPointCompensation) {
            vips_object_set(VIPS_OBJECT(op), "black-point-compensation", (gboolean)opts->blackPointCompensation, NULL);
        }
        if (opts->has_outputProfile) {
            vips_object_set(VIPS_OBJECT(op), "output-profile", opts->outputProfile, NULL);
        }
        if (opts->has_depth) {
            vips_object_set(VIPS_OBJECT(op), "depth", opts->depth, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_icc_import(VipsImage * input, VipsImage ** out_out, GenIccImportOpts *opts) {
    VipsOperation *op = vips_operation_new("icc_import");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_pcs) {
            vips_object_set(VIPS_OBJECT(op), "pcs", (int)opts->pcs, NULL);
        }
        if (opts->has_intent) {
            vips_object_set(VIPS_OBJECT(op), "intent", (int)opts->intent, NULL);
        }
        if (opts->has_blackPointCompensation) {
            vips_object_set(VIPS_OBJECT(op), "black-point-compensation", (gboolean)opts->blackPointCompensation, NULL);
        }
        if (opts->has_embedded) {
            vips_object_set(VIPS_OBJECT(op), "embedded", (gboolean)opts->embedded, NULL);
        }
        if (opts->has_inputProfile) {
            vips_object_set(VIPS_OBJECT(op), "input-profile", opts->inputProfile, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_rad2float(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("rad2float");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_sRGB2HSV(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("sRGB2HSV");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_sRGB2scRGB(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("sRGB2scRGB");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_scRGB2BW(VipsImage * input, VipsImage ** out_out, GenScRGB2BWOpts *opts) {
    VipsOperation *op = vips_operation_new("scRGB2BW");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_depth) {
            vips_object_set(VIPS_OBJECT(op), "depth", opts->depth, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_scRGB2XYZ(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("scRGB2XYZ");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_scRGB2sRGB(VipsImage * input, VipsImage ** out_out, GenScRGB2sRGBOpts *opts) {
    VipsOperation *op = vips_operation_new("scRGB2sRGB");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_depth) {
            vips_object_set(VIPS_OBJECT(op), "depth", opts->depth, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_uhdr2scRGB(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("uhdr2scRGB");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

