// Code generated by vipsgen. DO NOT EDIT.
#include "gen_conversion.h"

int gen_vips_arrayjoin(VipsImage **input, int input_n, VipsImage ** out_out, GenArrayjoinOpts *opts) {
    VipsOperation *op = vips_operation_new("arrayjoin");
    if (!op) return -1;

    {
        VipsArrayImage *arr = vips_array_image_new(input, input_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "in", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (opts) {
        if (opts->has_across) {
            vips_object_set(VIPS_OBJECT(op), "across", opts->across, NULL);
        }
        if (opts->has_shim) {
            vips_object_set(VIPS_OBJECT(op), "shim", opts->shim, NULL);
        }
        if (opts->has_background) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->background, opts->background_n);
                vips_object_set(VIPS_OBJECT(op), "background", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
        if (opts->has_halign) {
            vips_object_set(VIPS_OBJECT(op), "halign", (int)opts->halign, NULL);
        }
        if (opts->has_valign) {
            vips_object_set(VIPS_OBJECT(op), "valign", (int)opts->valign, NULL);
        }
        if (opts->has_hspacing) {
            vips_object_set(VIPS_OBJECT(op), "hspacing", opts->hspacing, NULL);
        }
        if (opts->has_vspacing) {
            vips_object_set(VIPS_OBJECT(op), "vspacing", opts->vspacing, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_autorot(VipsImage * input, VipsImage ** out_out, int * out_angle, int * out_flip) {
    VipsOperation *op = vips_operation_new("autorot");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);
    g_object_get(VIPS_OBJECT(op), "angle", out_angle, NULL);
    g_object_get(VIPS_OBJECT(op), "flip", out_flip, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandbool(VipsImage * input, VipsOperationBoolean boolean, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("bandbool");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "boolean", (int)boolean, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandfold(VipsImage * input, VipsImage ** out_out, GenBandfoldOpts *opts) {
    VipsOperation *op = vips_operation_new("bandfold");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_factor) {
            vips_object_set(VIPS_OBJECT(op), "factor", opts->factor, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandjoin(VipsImage **input, int input_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("bandjoin");
    if (!op) return -1;

    {
        VipsArrayImage *arr = vips_array_image_new(input, input_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "in", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandjoin_const(VipsImage * input, double * c, int c_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("bandjoin_const");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    {
        VipsArrayDouble *arr = vips_array_double_new(c, c_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "c", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandmean(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("bandmean");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandrank(VipsImage **input, int input_n, VipsImage ** out_out, GenBandrankOpts *opts) {
    VipsOperation *op = vips_operation_new("bandrank");
    if (!op) return -1;

    {
        VipsArrayImage *arr = vips_array_image_new(input, input_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "in", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (opts) {
        if (opts->has_index) {
            vips_object_set(VIPS_OBJECT(op), "index", opts->index, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_bandunfold(VipsImage * input, VipsImage ** out_out, GenBandunfoldOpts *opts) {
    VipsOperation *op = vips_operation_new("bandunfold");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_factor) {
            vips_object_set(VIPS_OBJECT(op), "factor", opts->factor, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_byteswap(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("byteswap");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_cache(VipsImage * input, VipsImage ** out_out, GenCacheOpts *opts) {
    VipsOperation *op = vips_operation_new("cache");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_maxTiles) {
            vips_object_set(VIPS_OBJECT(op), "max-tiles", opts->maxTiles, NULL);
        }
        if (opts->has_tileHeight) {
            vips_object_set(VIPS_OBJECT(op), "tile-height", opts->tileHeight, NULL);
        }
        if (opts->has_tileWidth) {
            vips_object_set(VIPS_OBJECT(op), "tile-width", opts->tileWidth, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_cast(VipsImage * input, VipsBandFormat format, VipsImage ** out_out, GenCastOpts *opts) {
    VipsOperation *op = vips_operation_new("cast");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "format", (int)format, NULL)) goto error;

    if (opts) {
        if (opts->has_shift) {
            vips_object_set(VIPS_OBJECT(op), "shift", (gboolean)opts->shift, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_composite2(VipsImage * base, VipsImage * overlay, VipsBlendMode mode, VipsImage ** out_out, GenComposite2Opts *opts) {
    VipsOperation *op = vips_operation_new("composite2");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "base", base, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "overlay", overlay, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "mode", (int)mode, NULL)) goto error;

    if (opts) {
        if (opts->has_x) {
            vips_object_set(VIPS_OBJECT(op), "x", opts->x, NULL);
        }
        if (opts->has_y) {
            vips_object_set(VIPS_OBJECT(op), "y", opts->y, NULL);
        }
        if (opts->has_compositingSpace) {
            vips_object_set(VIPS_OBJECT(op), "compositing-space", (int)opts->compositingSpace, NULL);
        }
        if (opts->has_premultiplied) {
            vips_object_set(VIPS_OBJECT(op), "premultiplied", (gboolean)opts->premultiplied, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_copy(VipsImage * input, VipsImage ** out_out, GenCopyOpts *opts) {
    VipsOperation *op = vips_operation_new("copy");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_width) {
            vips_object_set(VIPS_OBJECT(op), "width", opts->width, NULL);
        }
        if (opts->has_height) {
            vips_object_set(VIPS_OBJECT(op), "height", opts->height, NULL);
        }
        if (opts->has_bands) {
            vips_object_set(VIPS_OBJECT(op), "bands", opts->bands, NULL);
        }
        if (opts->has_format) {
            vips_object_set(VIPS_OBJECT(op), "format", (int)opts->format, NULL);
        }
        if (opts->has_coding) {
            vips_object_set(VIPS_OBJECT(op), "coding", (int)opts->coding, NULL);
        }
        if (opts->has_interpretation) {
            vips_object_set(VIPS_OBJECT(op), "interpretation", (int)opts->interpretation, NULL);
        }
        if (opts->has_xres) {
            vips_object_set(VIPS_OBJECT(op), "xres", opts->xres, NULL);
        }
        if (opts->has_yres) {
            vips_object_set(VIPS_OBJECT(op), "yres", opts->yres, NULL);
        }
        if (opts->has_xoffset) {
            vips_object_set(VIPS_OBJECT(op), "xoffset", opts->xoffset, NULL);
        }
        if (opts->has_yoffset) {
            vips_object_set(VIPS_OBJECT(op), "yoffset", opts->yoffset, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_extract_band(VipsImage * input, int band, VipsImage ** out_out, GenExtractBandOpts *opts) {
    VipsOperation *op = vips_operation_new("extract_band");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "band", band, NULL)) goto error;

    if (opts) {
        if (opts->has_n) {
            vips_object_set(VIPS_OBJECT(op), "n", opts->n, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_falsecolour(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("falsecolour");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_flatten(VipsImage * input, VipsImage ** out_out, GenFlattenOpts *opts) {
    VipsOperation *op = vips_operation_new("flatten");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_background) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->background, opts->background_n);
                vips_object_set(VIPS_OBJECT(op), "background", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
        if (opts->has_maxAlpha) {
            vips_object_set(VIPS_OBJECT(op), "max-alpha", opts->maxAlpha, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_gamma(VipsImage * input, VipsImage ** out_out, GenGammaOpts *opts) {
    VipsOperation *op = vips_operation_new("gamma");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_exponent) {
            vips_object_set(VIPS_OBJECT(op), "exponent", opts->exponent, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_gravity(VipsImage * input, VipsCompassDirection direction, int width, int height, VipsImage ** out_out, GenGravityOpts *opts) {
    VipsOperation *op = vips_operation_new("gravity");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "direction", (int)direction, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "width", width, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "height", height, NULL)) goto error;

    if (opts) {
        if (opts->has_extend) {
            vips_object_set(VIPS_OBJECT(op), "extend", (int)opts->extend, NULL);
        }
        if (opts->has_background) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->background, opts->background_n);
                vips_object_set(VIPS_OBJECT(op), "background", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_grid(VipsImage * input, int tileHeight, int across, int down, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("grid");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "tile-height", tileHeight, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "across", across, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "down", down, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_ifthenelse(VipsImage * cond, VipsImage * in1, VipsImage * in2, VipsImage ** out_out, GenIfthenelseOpts *opts) {
    VipsOperation *op = vips_operation_new("ifthenelse");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "cond", cond, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "in1", in1, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "in2", in2, NULL)) goto error;

    if (opts) {
        if (opts->has_blend) {
            vips_object_set(VIPS_OBJECT(op), "blend", (gboolean)opts->blend, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_insert(VipsImage * main, VipsImage * sub, int x, int y, VipsImage ** out_out, GenInsertOpts *opts) {
    VipsOperation *op = vips_operation_new("insert");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "main", main, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "sub", sub, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "x", x, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "y", y, NULL)) goto error;

    if (opts) {
        if (opts->has_expand) {
            vips_object_set(VIPS_OBJECT(op), "expand", (gboolean)opts->expand, NULL);
        }
        if (opts->has_background) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->background, opts->background_n);
                vips_object_set(VIPS_OBJECT(op), "background", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_join(VipsImage * in1, VipsImage * in2, VipsDirection direction, VipsImage ** out_out, GenJoinOpts *opts) {
    VipsOperation *op = vips_operation_new("join");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in1", in1, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "in2", in2, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "direction", (int)direction, NULL)) goto error;

    if (opts) {
        if (opts->has_expand) {
            vips_object_set(VIPS_OBJECT(op), "expand", (gboolean)opts->expand, NULL);
        }
        if (opts->has_shim) {
            vips_object_set(VIPS_OBJECT(op), "shim", opts->shim, NULL);
        }
        if (opts->has_background) {
            {
                VipsArrayDouble *arr = vips_array_double_new(opts->background, opts->background_n);
                vips_object_set(VIPS_OBJECT(op), "background", arr, NULL);
                vips_area_unref(VIPS_AREA(arr));
            }
        }
        if (opts->has_align) {
            vips_object_set(VIPS_OBJECT(op), "align", (int)opts->align, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_linecache(VipsImage * input, VipsImage ** out_out, GenLinecacheOpts *opts) {
    VipsOperation *op = vips_operation_new("linecache");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_tileHeight) {
            vips_object_set(VIPS_OBJECT(op), "tile-height", opts->tileHeight, NULL);
        }
        if (opts->has_access) {
            vips_object_set(VIPS_OBJECT(op), "access", (int)opts->access, NULL);
        }
        if (opts->has_threaded) {
            vips_object_set(VIPS_OBJECT(op), "threaded", (gboolean)opts->threaded, NULL);
        }
        if (opts->has_persistent) {
            vips_object_set(VIPS_OBJECT(op), "persistent", (gboolean)opts->persistent, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_msb(VipsImage * input, VipsImage ** out_out, GenMsbOpts *opts) {
    VipsOperation *op = vips_operation_new("msb");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_band) {
            vips_object_set(VIPS_OBJECT(op), "band", opts->band, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_premultiply(VipsImage * input, VipsImage ** out_out, GenPremultiplyOpts *opts) {
    VipsOperation *op = vips_operation_new("premultiply");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_maxAlpha) {
            vips_object_set(VIPS_OBJECT(op), "max-alpha", opts->maxAlpha, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_recomb(VipsImage * input, VipsImage * m, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("recomb");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "m", m, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_replicate(VipsImage * input, int across, int down, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("replicate");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "across", across, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "down", down, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_rot(VipsImage * input, VipsAngle angle, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("rot");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "angle", (int)angle, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_rot45(VipsImage * input, VipsImage ** out_out, GenRot45Opts *opts) {
    VipsOperation *op = vips_operation_new("rot45");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_angle) {
            vips_object_set(VIPS_OBJECT(op), "angle", (int)opts->angle, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_scale(VipsImage * input, VipsImage ** out_out, GenScaleOpts *opts) {
    VipsOperation *op = vips_operation_new("scale");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_exp) {
            vips_object_set(VIPS_OBJECT(op), "exp", opts->exp, NULL);
        }
        if (opts->has_log) {
            vips_object_set(VIPS_OBJECT(op), "log", (gboolean)opts->log, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_sequential(VipsImage * input, VipsImage ** out_out, GenSequentialOpts *opts) {
    VipsOperation *op = vips_operation_new("sequential");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_tileHeight) {
            vips_object_set(VIPS_OBJECT(op), "tile-height", opts->tileHeight, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_subsample(VipsImage * input, int xfac, int yfac, VipsImage ** out_out, GenSubsampleOpts *opts) {
    VipsOperation *op = vips_operation_new("subsample");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "input", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "xfac", xfac, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "yfac", yfac, NULL)) goto error;

    if (opts) {
        if (opts->has_point) {
            vips_object_set(VIPS_OBJECT(op), "point", (gboolean)opts->point, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_tilecache(VipsImage * input, VipsImage ** out_out, GenTilecacheOpts *opts) {
    VipsOperation *op = vips_operation_new("tilecache");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_tileWidth) {
            vips_object_set(VIPS_OBJECT(op), "tile-width", opts->tileWidth, NULL);
        }
        if (opts->has_tileHeight) {
            vips_object_set(VIPS_OBJECT(op), "tile-height", opts->tileHeight, NULL);
        }
        if (opts->has_maxTiles) {
            vips_object_set(VIPS_OBJECT(op), "max-tiles", opts->maxTiles, NULL);
        }
        if (opts->has_access) {
            vips_object_set(VIPS_OBJECT(op), "access", (int)opts->access, NULL);
        }
        if (opts->has_threaded) {
            vips_object_set(VIPS_OBJECT(op), "threaded", (gboolean)opts->threaded, NULL);
        }
        if (opts->has_persistent) {
            vips_object_set(VIPS_OBJECT(op), "persistent", (gboolean)opts->persistent, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_transpose3d(VipsImage * input, VipsImage ** out_out, GenTranspose3dOpts *opts) {
    VipsOperation *op = vips_operation_new("transpose3d");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_pageHeight) {
            vips_object_set(VIPS_OBJECT(op), "page-height", opts->pageHeight, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_unpremultiply(VipsImage * input, VipsImage ** out_out, GenUnpremultiplyOpts *opts) {
    VipsOperation *op = vips_operation_new("unpremultiply");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_maxAlpha) {
            vips_object_set(VIPS_OBJECT(op), "max-alpha", opts->maxAlpha, NULL);
        }
        if (opts->has_alphaBand) {
            vips_object_set(VIPS_OBJECT(op), "alpha-band", opts->alphaBand, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_wrap(VipsImage * input, VipsImage ** out_out, GenWrapOpts *opts) {
    VipsOperation *op = vips_operation_new("wrap");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_x) {
            vips_object_set(VIPS_OBJECT(op), "x", opts->x, NULL);
        }
        if (opts->has_y) {
            vips_object_set(VIPS_OBJECT(op), "y", opts->y, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_zoom(VipsImage * input, int xfac, int yfac, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("zoom");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "input", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "xfac", xfac, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "yfac", yfac, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

