// Code generated by vipsgen. DO NOT EDIT.
package vips

// This file is intentionally minimal. Helper functions used by generated code
// (incOpCounter, handleImageError, handleVipsError, boolToInt) are defined
// in the hand-written vips package files.
