// Code generated by vipsgen. DO NOT EDIT.
#ifndef GEN_CONVOLUTION_H
#define GEN_CONVOLUTION_H

#include <stdlib.h>
#include <vips/vips.h>

typedef struct {
    int has_sigma;
    double sigma;
    int has_precision;
    VipsPrecision precision;
} GenCannyOpts;

int gen_vips_canny(VipsImage * input, VipsImage ** out_out, GenCannyOpts *opts);

typedef struct {
    int has_times;
    int times;
    int has_angle;
    VipsAngle45 angle;
    int has_combine;
    VipsCombine combine;
    int has_precision;
    VipsPrecision precision;
    int has_layers;
    int layers;
    int has_cluster;
    int cluster;
} GenCompassOpts;

int gen_vips_compass(VipsImage * input, VipsImage * mask, VipsImage ** out_out, GenCompassOpts *opts);

typedef struct {
    int has_precision;
    VipsPrecision precision;
    int has_layers;
    int layers;
    int has_cluster;
    int cluster;
} GenConvOpts;

int gen_vips_conv(VipsImage * input, VipsImage * mask, VipsImage ** out_out, GenConvOpts *opts);

typedef struct {
    int has_layers;
    int layers;
    int has_cluster;
    int cluster;
} GenConvaOpts;

int gen_vips_conva(VipsImage * input, VipsImage * mask, VipsImage ** out_out, GenConvaOpts *opts);

typedef struct {
    int has_layers;
    int layers;
} GenConvasepOpts;

int gen_vips_convasep(VipsImage * input, VipsImage * mask, VipsImage ** out_out, GenConvasepOpts *opts);

int gen_vips_convf(VipsImage * input, VipsImage * mask, VipsImage ** out_out);

int gen_vips_convi(VipsImage * input, VipsImage * mask, VipsImage ** out_out);

typedef struct {
    int has_precision;
    VipsPrecision precision;
    int has_layers;
    int layers;
    int has_cluster;
    int cluster;
} GenConvsepOpts;

int gen_vips_convsep(VipsImage * input, VipsImage * mask, VipsImage ** out_out, GenConvsepOpts *opts);

int gen_vips_fastcor(VipsImage * input, VipsImage * ref, VipsImage ** out_out);

typedef struct {
    int has_minAmpl;
    double minAmpl;
    int has_precision;
    VipsPrecision precision;
} GenGaussblurOpts;

int gen_vips_gaussblur(VipsImage * input, double sigma, VipsImage ** out_out, GenGaussblurOpts *opts);

int gen_vips_prewitt(VipsImage * input, VipsImage ** out_out);

int gen_vips_scharr(VipsImage * input, VipsImage ** out_out);

typedef struct {
    int has_sigma;
    double sigma;
    int has_x1;
    double x1;
    int has_y2;
    double y2;
    int has_y3;
    double y3;
    int has_m1;
    double m1;
    int has_m2;
    double m2;
} GenSharpenOpts;

int gen_vips_sharpen(VipsImage * input, VipsImage ** out_out, GenSharpenOpts *opts);

int gen_vips_sobel(VipsImage * input, VipsImage ** out_out);

int gen_vips_spcor(VipsImage * input, VipsImage * ref, VipsImage ** out_out);

#endif
