// Code generated by vipsgen. DO NOT EDIT.
#ifndef GEN_MORPHOLOGY_H
#define GEN_MORPHOLOGY_H

#include <stdlib.h>
#include <vips/vips.h>

int gen_vips_countlines(VipsImage * input, VipsDirection direction, double * out_nolines);

int gen_vips_fill_nearest(VipsImage * input, VipsImage ** out_out, VipsImage ** out_distance);

int gen_vips_labelregions(VipsImage * input, VipsImage ** out_mask, int * out_segments);

int gen_vips_morph(VipsImage * input, VipsImage * mask, VipsOperationMorphology morph, VipsImage ** out_out);

int gen_vips_rank(VipsImage * input, int width, int height, int index, VipsImage ** out_out);

#endif
