// Code generated by vipsgen. DO NOT EDIT.
package vips

// #include "gen_morphology.h"
import "C"

import "unsafe"

// Ensure imports are used.
var _ = unsafe.Pointer(nil)

// vipsGenCountlines calls the vips countlines operation.
// count lines in an image
func vipsGenCountlines(input *C.VipsImage, direction Direction) (float64, error) {
	incOpCounter("countlines")

	var out_nolines C.double

	ret := C.gen_vips_countlines(input, C.VipsDirection(direction), &out_nolines)
	if ret != 0 {
		return 0, handleVipsError()
	}

	return float64(out_nolines), nil
}

// vipsGenFillNearest calls the vips fill_nearest operation.
// fill image zeros with nearest non-zero pixel
func vipsGenFillNearest(input *C.VipsImage) (*C.VipsImage, *C.VipsImage, error) {
	incOpCounter("fill_nearest")

	var out_out *C.VipsImage
	var out_distance *C.VipsImage

	ret := C.gen_vips_fill_nearest(input, &out_out, &out_distance)
	if ret != 0 {
		return nil, nil, handleImageError(out_out)
	}

	return out_out, out_distance, nil
}

// vipsGenLabelregions calls the vips labelregions operation.
// label regions in an image
func vipsGenLabelregions(input *C.VipsImage) (*C.VipsImage, int, error) {
	incOpCounter("labelregions")

	var out_mask *C.VipsImage
	var out_segments C.int

	ret := C.gen_vips_labelregions(input, &out_mask, &out_segments)
	if ret != 0 {
		return nil, 0, handleImageError(out_mask)
	}

	return out_mask, int(out_segments), nil
}

// vipsGenMorph calls the vips morph operation.
// morphology operation
func vipsGenMorph(input *C.VipsImage, mask *C.VipsImage, morph OperationMorphology) (*C.VipsImage, error) {
	incOpCounter("morph")

	var out_out *C.VipsImage

	ret := C.gen_vips_morph(input, mask, C.VipsOperationMorphology(morph), &out_out)
	if ret != 0 {
		return nil, handleImageError(out_out)
	}

	return out_out, nil
}

// vipsGenRank calls the vips rank operation.
// rank filter
func vipsGenRank(input *C.VipsImage, width int, height int, index int) (*C.VipsImage, error) {
	incOpCounter("rank")

	var out_out *C.VipsImage

	ret := C.gen_vips_rank(input, C.int(width), C.int(height), C.int(index), &out_out)
	if ret != 0 {
		return nil, handleImageError(out_out)
	}

	return out_out, nil
}

