// Code generated by vipsgen. DO NOT EDIT.
#ifndef GEN_CREATE_H
#define GEN_CREATE_H

#include <stdlib.h>
#include <vips/vips.h>

typedef struct {
    int has_bands;
    int bands;
} GenBlackOpts;

int gen_vips_black(int width, int height, VipsImage ** out_out, GenBlackOpts *opts);

int gen_vips_buildlut(VipsImage * input, VipsImage ** out_out);

typedef struct {
    int has_uchar;
    int uchar;
    int has_factor;
    double factor;
} GenEyeOpts;

int gen_vips_eye(int width, int height, VipsImage ** out_out, GenEyeOpts *opts);

int gen_vips_fractsurf(int width, int height, double fractalDimension, VipsImage ** out_out);

typedef struct {
    int has_separable;
    int separable;
    int has_precision;
    VipsPrecision precision;
} GenGaussmatOpts;

int gen_vips_gaussmat(double sigma, double minAmpl, VipsImage ** out_out, GenGaussmatOpts *opts);

typedef struct {
    int has_sigma;
    double sigma;
    int has_mean;
    double mean;
    int has_seed;
    int seed;
} GenGaussnoiseOpts;

int gen_vips_gaussnoise(int width, int height, VipsImage ** out_out, GenGaussnoiseOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
} GenGreyOpts;

int gen_vips_grey(int width, int height, VipsImage ** out_out, GenGreyOpts *opts);

typedef struct {
    int has_bands;
    int bands;
    int has_ushort;
    int ushort;
    int has_size;
    int size;
} GenIdentityOpts;

int gen_vips_identity(VipsImage ** out_out, GenIdentityOpts *opts);

typedef struct {
    int has_size;
    int size;
} GenInvertlutOpts;

int gen_vips_invertlut(VipsImage * input, VipsImage ** out_out, GenInvertlutOpts *opts);

typedef struct {
    int has_separable;
    int separable;
    int has_precision;
    VipsPrecision precision;
} GenLogmatOpts;

int gen_vips_logmat(double sigma, double minAmpl, VipsImage ** out_out, GenLogmatOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskButterworthOpts;

int gen_vips_mask_butterworth(int width, int height, double order, double frequencyCutoff, double amplitudeCutoff, VipsImage ** out_out, GenMaskButterworthOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskButterworthBandOpts;

int gen_vips_mask_butterworth_band(int width, int height, double order, double frequencyCutoffX, double frequencyCutoffY, double radius, double amplitudeCutoff, VipsImage ** out_out, GenMaskButterworthBandOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskButterworthRingOpts;

int gen_vips_mask_butterworth_ring(int width, int height, double order, double frequencyCutoff, double amplitudeCutoff, double ringwidth, VipsImage ** out_out, GenMaskButterworthRingOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskFractalOpts;

int gen_vips_mask_fractal(int width, int height, double fractalDimension, VipsImage ** out_out, GenMaskFractalOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskGaussianOpts;

int gen_vips_mask_gaussian(int width, int height, double frequencyCutoff, double amplitudeCutoff, VipsImage ** out_out, GenMaskGaussianOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskGaussianBandOpts;

int gen_vips_mask_gaussian_band(int width, int height, double frequencyCutoffX, double frequencyCutoffY, double radius, double amplitudeCutoff, VipsImage ** out_out, GenMaskGaussianBandOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskGaussianRingOpts;

int gen_vips_mask_gaussian_ring(int width, int height, double frequencyCutoff, double amplitudeCutoff, double ringwidth, VipsImage ** out_out, GenMaskGaussianRingOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskIdealOpts;

int gen_vips_mask_ideal(int width, int height, double frequencyCutoff, VipsImage ** out_out, GenMaskIdealOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskIdealBandOpts;

int gen_vips_mask_ideal_band(int width, int height, double frequencyCutoffX, double frequencyCutoffY, double radius, VipsImage ** out_out, GenMaskIdealBandOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_nodc;
    int nodc;
    int has_reject;
    int reject;
    int has_optical;
    int optical;
} GenMaskIdealRingOpts;

int gen_vips_mask_ideal_ring(int width, int height, double frequencyCutoff, double ringwidth, VipsImage ** out_out, GenMaskIdealRingOpts *opts);

typedef struct {
    int has_cellSize;
    int cellSize;
    int has_uchar;
    int uchar;
    int has_seed;
    int seed;
} GenPerlinOpts;

int gen_vips_perlin(int width, int height, VipsImage ** out_out, GenPerlinOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
    int has_hfreq;
    double hfreq;
    int has_vfreq;
    double vfreq;
} GenSinesOpts;

int gen_vips_sines(int width, int height, VipsImage ** out_out, GenSinesOpts *opts);

typedef struct {
    int has_inMax;
    int inMax;
    int has_outMax;
    int outMax;
    int has_Lb;
    double Lb;
    int has_Lw;
    double Lw;
    int has_Ps;
    double Ps;
    int has_Pm;
    double Pm;
    int has_Ph;
    double Ph;
    int has_S;
    double S;
    int has_M;
    double M;
    int has_H;
    double H;
} GenTonelutOpts;

int gen_vips_tonelut(VipsImage ** out_out, GenTonelutOpts *opts);

typedef struct {
    int has_cellSize;
    int cellSize;
    int has_seed;
    int seed;
} GenWorleyOpts;

int gen_vips_worley(int width, int height, VipsImage ** out_out, GenWorleyOpts *opts);

typedef struct {
    int has_csize;
    int csize;
    int has_dsize;
    int dsize;
    int has_esize;
    int esize;
} GenXyzOpts;

int gen_vips_xyz(int width, int height, VipsImage ** out_out, GenXyzOpts *opts);

typedef struct {
    int has_uchar;
    int uchar;
} GenZoneOpts;

int gen_vips_zone(int width, int height, VipsImage ** out_out, GenZoneOpts *opts);

#endif
