// Code generated by vipsgen. DO NOT EDIT.
#include "gen_arithmetic.h"

int gen_vips_abs(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("abs");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_add(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("add");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_avg(VipsImage * input, double * out_out) {
    VipsOperation *op = vips_operation_new("avg");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_boolean(VipsImage * left, VipsImage * right, VipsOperationBoolean boolean, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("boolean");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "boolean", (int)boolean, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_boolean_const(VipsImage * input, VipsOperationBoolean boolean, double * c, int c_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("boolean_const");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "boolean", (int)boolean, NULL)) goto error;
    {
        VipsArrayDouble *arr = vips_array_double_new(c, c_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "c", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_clamp(VipsImage * input, VipsImage ** out_out, GenClampOpts *opts) {
    VipsOperation *op = vips_operation_new("clamp");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_min) {
            vips_object_set(VIPS_OBJECT(op), "min", opts->min, NULL);
        }
        if (opts->has_max) {
            vips_object_set(VIPS_OBJECT(op), "max", opts->max, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_complex(VipsImage * input, VipsOperationComplex cmplx, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("complex");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "cmplx", (int)cmplx, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_complex2(VipsImage * left, VipsImage * right, VipsOperationComplex2 cmplx, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("complex2");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "cmplx", (int)cmplx, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_complexform(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("complexform");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_complexget(VipsImage * input, VipsOperationComplexget get, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("complexget");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "get", (int)get, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_deviate(VipsImage * input, double * out_out) {
    VipsOperation *op = vips_operation_new("deviate");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_divide(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("divide");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_hist_find(VipsImage * input, VipsImage ** out_out, GenHistFindOpts *opts) {
    VipsOperation *op = vips_operation_new("hist_find");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_band) {
            vips_object_set(VIPS_OBJECT(op), "band", opts->band, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_hist_find_indexed(VipsImage * input, VipsImage * index, VipsImage ** out_out, GenHistFindIndexedOpts *opts) {
    VipsOperation *op = vips_operation_new("hist_find_indexed");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "index", index, NULL)) goto error;

    if (opts) {
        if (opts->has_combine) {
            vips_object_set(VIPS_OBJECT(op), "combine", (int)opts->combine, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_hist_find_ndim(VipsImage * input, VipsImage ** out_out, GenHistFindNdimOpts *opts) {
    VipsOperation *op = vips_operation_new("hist_find_ndim");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_bins) {
            vips_object_set(VIPS_OBJECT(op), "bins", opts->bins, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_hough_circle(VipsImage * input, VipsImage ** out_out, GenHoughCircleOpts *opts) {
    VipsOperation *op = vips_operation_new("hough_circle");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_scale) {
            vips_object_set(VIPS_OBJECT(op), "scale", opts->scale, NULL);
        }
        if (opts->has_minRadius) {
            vips_object_set(VIPS_OBJECT(op), "min-radius", opts->minRadius, NULL);
        }
        if (opts->has_maxRadius) {
            vips_object_set(VIPS_OBJECT(op), "max-radius", opts->maxRadius, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_hough_line(VipsImage * input, VipsImage ** out_out, GenHoughLineOpts *opts) {
    VipsOperation *op = vips_operation_new("hough_line");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (opts) {
        if (opts->has_width) {
            vips_object_set(VIPS_OBJECT(op), "width", opts->width, NULL);
        }
        if (opts->has_height) {
            vips_object_set(VIPS_OBJECT(op), "height", opts->height, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_invert(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("invert");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_linear(VipsImage * input, double * a, int a_n, double * b, int b_n, VipsImage ** out_out, GenLinearOpts *opts) {
    VipsOperation *op = vips_operation_new("linear");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    {
        VipsArrayDouble *arr = vips_array_double_new(a, a_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "a", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }
    {
        VipsArrayDouble *arr = vips_array_double_new(b, b_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "b", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (opts) {
        if (opts->has_uchar) {
            vips_object_set(VIPS_OBJECT(op), "uchar", (gboolean)opts->uchar, NULL);
        }
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_math(VipsImage * input, VipsOperationMath math, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("math");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "math", (int)math, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_math2(VipsImage * left, VipsImage * right, VipsOperationMath2 math2, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("math2");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "math2", (int)math2, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_math2_const(VipsImage * input, VipsOperationMath2 math2, double * c, int c_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("math2_const");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "math2", (int)math2, NULL)) goto error;
    {
        VipsArrayDouble *arr = vips_array_double_new(c, c_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "c", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_matrixinvert(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("matrixinvert");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_matrixmultiply(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("matrixmultiply");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_maxpair(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("maxpair");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_minpair(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("minpair");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_multiply(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("multiply");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_profile(VipsImage * input, VipsImage ** out_columns, VipsImage ** out_rows) {
    VipsOperation *op = vips_operation_new("profile");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "columns", out_columns, NULL);
    g_object_get(VIPS_OBJECT(op), "rows", out_rows, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_project(VipsImage * input, VipsImage ** out_columns, VipsImage ** out_rows) {
    VipsOperation *op = vips_operation_new("project");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "columns", out_columns, NULL);
    g_object_get(VIPS_OBJECT(op), "rows", out_rows, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_relational(VipsImage * left, VipsImage * right, VipsOperationRelational relational, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("relational");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "relational", (int)relational, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_relational_const(VipsImage * input, VipsOperationRelational relational, double * c, int c_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("relational_const");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "relational", (int)relational, NULL)) goto error;
    {
        VipsArrayDouble *arr = vips_array_double_new(c, c_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "c", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_remainder(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("remainder");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_remainder_const(VipsImage * input, double * c, int c_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("remainder_const");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    {
        VipsArrayDouble *arr = vips_array_double_new(c, c_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "c", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_round(VipsImage * input, VipsOperationRound round, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("round");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "round", (int)round, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_sign(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("sign");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_stats(VipsImage * input, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("stats");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_subtract(VipsImage * left, VipsImage * right, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("subtract");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "left", left, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "right", right, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_sum(VipsImage **input, int input_n, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("sum");
    if (!op) return -1;

    {
        VipsArrayImage *arr = vips_array_image_new(input, input_n);
        int ret = vips_object_set(VIPS_OBJECT(op), "in", arr, NULL);
        vips_area_unref(VIPS_AREA(arr));
        if (ret) goto error;
    }

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

