// Code generated by vipsgen. DO NOT EDIT.
#include "gen_morphology.h"

int gen_vips_countlines(VipsImage * input, VipsDirection direction, double * out_nolines) {
    VipsOperation *op = vips_operation_new("countlines");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "direction", (int)direction, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "nolines", out_nolines, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_fill_nearest(VipsImage * input, VipsImage ** out_out, VipsImage ** out_distance) {
    VipsOperation *op = vips_operation_new("fill_nearest");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);
    g_object_get(VIPS_OBJECT(op), "distance", out_distance, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_labelregions(VipsImage * input, VipsImage ** out_mask, int * out_segments) {
    VipsOperation *op = vips_operation_new("labelregions");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "mask", out_mask, NULL);
    g_object_get(VIPS_OBJECT(op), "segments", out_segments, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_morph(VipsImage * input, VipsImage * mask, VipsOperationMorphology morph, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("morph");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "mask", mask, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "morph", (int)morph, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

int gen_vips_rank(VipsImage * input, int width, int height, int index, VipsImage ** out_out) {
    VipsOperation *op = vips_operation_new("rank");
    if (!op) return -1;

    if (vips_object_set(VIPS_OBJECT(op), "in", input, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "width", width, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "height", height, NULL)) goto error;
    if (vips_object_set(VIPS_OBJECT(op), "index", index, NULL)) goto error;

    if (vips_cache_operation_buildp(&op)) goto error;

    g_object_get(VIPS_OBJECT(op), "out", out_out, NULL);

    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return 0;

error:
    vips_object_unref_outputs(VIPS_OBJECT(op));
    g_object_unref(op);
    return -1;
}

