// Code generated by vipsgen. DO NOT EDIT.
#ifndef GEN_RESAMPLE_H
#define GEN_RESAMPLE_H

#include <stdlib.h>
#include <vips/vips.h>

typedef struct {
    int has_interpolate;
    VipsInterpolate *interpolate;
    int has_oarea;
    int *oarea; int oarea_n;
    int has_odx;
    double odx;
    int has_ody;
    double ody;
    int has_idx;
    double idx;
    int has_idy;
    double idy;
    int has_background;
    double *background; int background_n;
    int has_premultiplied;
    int premultiplied;
    int has_extend;
    VipsExtend extend;
} GenAffineOpts;

int gen_vips_affine(VipsImage * input, double * matrix, int matrix_n, VipsImage ** out_out, GenAffineOpts *opts);

typedef struct {
    int has_gamma;
    double gamma;
    int has_intOutput;
    int intOutput;
} GenGlobalbalanceOpts;

int gen_vips_globalbalance(VipsImage * input, VipsImage ** out_out, GenGlobalbalanceOpts *opts);

typedef struct {
    int has_interpolate;
    VipsInterpolate *interpolate;
    int has_background;
    double *background; int background_n;
    int has_premultiplied;
    int premultiplied;
    int has_extend;
    VipsExtend extend;
} GenMapimOpts;

int gen_vips_mapim(VipsImage * input, VipsImage * index, VipsImage ** out_out, GenMapimOpts *opts);

typedef struct {
    int has_hwindow;
    int hwindow;
    int has_harea;
    int harea;
    int has_search;
    int search;
    int has_interpolate;
    VipsInterpolate *interpolate;
} GenMatchOpts;

int gen_vips_match(VipsImage * ref, VipsImage * sec, int xr1, int yr1, int xs1, int ys1, int xr2, int yr2, int xs2, int ys2, VipsImage ** out_out, GenMatchOpts *opts);

typedef struct {
    int has_mblend;
    int mblend;
} GenMergeOpts;

int gen_vips_merge(VipsImage * ref, VipsImage * sec, VipsDirection direction, int dx, int dy, VipsImage ** out_out, GenMergeOpts *opts);

typedef struct {
    int has_hwindow;
    int hwindow;
    int has_harea;
    int harea;
    int has_mblend;
    int mblend;
    int has_bandno;
    int bandno;
} GenMosaicOpts;

int gen_vips_mosaic(VipsImage * ref, VipsImage * sec, VipsDirection direction, int xref, int yref, int xsec, int ysec, VipsImage ** out_out, int * out_dx0, int * out_dy0, double * out_scale1, double * out_angle1, double * out_dy1, double * out_dx1, GenMosaicOpts *opts);

typedef struct {
    int has_hwindow;
    int hwindow;
    int has_harea;
    int harea;
    int has_search;
    int search;
    int has_interpolate;
    VipsInterpolate *interpolate;
    int has_mblend;
    int mblend;
} GenMosaic1Opts;

int gen_vips_mosaic1(VipsImage * ref, VipsImage * sec, VipsDirection direction, int xr1, int yr1, int xs1, int ys1, int xr2, int yr2, int xs2, int ys2, VipsImage ** out_out, GenMosaic1Opts *opts);

typedef struct {
    int has_interpolate;
    VipsInterpolate *interpolate;
} GenQuadraticOpts;

int gen_vips_quadratic(VipsImage * input, VipsImage * coeff, VipsImage ** out_out, GenQuadraticOpts *opts);

typedef struct {
    int has_kernel;
    VipsKernel kernel;
    int has_gap;
    double gap;
} GenReduceOpts;

int gen_vips_reduce(VipsImage * input, double hshrink, double vshrink, VipsImage ** out_out, GenReduceOpts *opts);

typedef struct {
    int has_kernel;
    VipsKernel kernel;
    int has_gap;
    double gap;
} GenReducehOpts;

int gen_vips_reduceh(VipsImage * input, double hshrink, VipsImage ** out_out, GenReducehOpts *opts);

typedef struct {
    int has_kernel;
    VipsKernel kernel;
    int has_gap;
    double gap;
} GenReducevOpts;

int gen_vips_reducev(VipsImage * input, double vshrink, VipsImage ** out_out, GenReducevOpts *opts);

int gen_vips_remosaic(VipsImage * input, const char * oldStr, const char * newStr, VipsImage ** out_out);

typedef struct {
    int has_interpolate;
    VipsInterpolate *interpolate;
    int has_background;
    double *background; int background_n;
    int has_odx;
    double odx;
    int has_ody;
    double ody;
    int has_idx;
    double idx;
    int has_idy;
    double idy;
} GenRotateOpts;

int gen_vips_rotate(VipsImage * input, double angle, VipsImage ** out_out, GenRotateOpts *opts);

typedef struct {
    int has_ceil;
    int ceil;
} GenShrinkOpts;

int gen_vips_shrink(VipsImage * input, double hshrink, double vshrink, VipsImage ** out_out, GenShrinkOpts *opts);

typedef struct {
    int has_ceil;
    int ceil;
} GenShrinkhOpts;

int gen_vips_shrinkh(VipsImage * input, int hshrink, VipsImage ** out_out, GenShrinkhOpts *opts);

typedef struct {
    int has_ceil;
    int ceil;
} GenShrinkvOpts;

int gen_vips_shrinkv(VipsImage * input, int vshrink, VipsImage ** out_out, GenShrinkvOpts *opts);

typedef struct {
    int has_scale;
    double scale;
    int has_angle;
    double angle;
    int has_interpolate;
    VipsInterpolate *interpolate;
    int has_background;
    double *background; int background_n;
    int has_odx;
    double odx;
    int has_ody;
    double ody;
    int has_idx;
    double idx;
    int has_idy;
    double idy;
} GenSimilarityOpts;

int gen_vips_similarity(VipsImage * input, VipsImage ** out_out, GenSimilarityOpts *opts);

#endif
